apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: aks-demo
type: Opaque
stringData:
  appinsights-connection-string: "InstrumentationKey=24770f9a-d604-46ce-94fb-febfcf999d35;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=71fcaf8e-9b0b-4a77-9019-66c039d26b40"
