apiVersion: v1
kind: Service
metadata:
  name: aks-demo-api-service
  namespace: aks-demo
  labels:
    app: aks-demo-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: aks-demo-api
